sudo: true
os: trusty
node_js: '7'
cache: false

before_install:
  - openssl aes-256-cbc -K $encrypted_79a2f6093848_key -iv $encrypted_79a2f6093848_iv -in assets/server.key.enc -out assets/server.key -d
  - export URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  - export SFDX_AUTOUPDATE_DISABLE=false
  - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
  - export SFDX_DOMAIN_RETRY=300
  - export SFDX_DISABLE_APP_HUB=true
  - export SFDX_LOG_LEVEL=DEBUG
  - mkdir sfdx
  - wget -qO- $URL | tar xJ -C sfdx --strip-components 1
  - "./sfdx/install"
  - export PATH=./sfdx/$(pwd):$PATH
  - sfdx update
  - sfdx --version
  - sfdx plugins --core
  - npm install apexcov coveralls -g
  - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a DevHub
  - echo y | sfdx plugins:install @mavens/sfdx-commands
script:
  - sfdx force:org:create -v DevHub -s -f scratchdef.json -a ciorg --wait 2
  - sfdx force:org:display -u ciorg
  - sfdx force:source:push -u ciorg
  - mkdir coverage
  - sfdx force:apex:test:run -u ciorg --codecoverage --testlevel=RunLocalTests --resultformat=human --outputdir=coverage --wait 10
  - sfdx mavens:ci:lcov
  - sfdx force:org:delete -u ciorg -p
  - cat ./coverage/lcov.info | coveralls
